### ISSUE TITLE
Prototype?

### ISSUE THREAD

**Issue by polluks** [tdolphin-org/AmigaOS.MUI.cpp.wrapper#1]
https://github.com/tdolphin-org/AmigaOS.MUI.cpp.wrapper/blob/10ecb6c1a96a1084e2a1a99e7235436b67fffad8/examples/basic/Main.hpp#L11
https://stackoverflow.com/questions/38543876/prototype-of-main-function-in-c-or-c

**Comment by tdolphin-org** [comment]
@polluks could You clarify what is wrong with having declaration of main() in header?

**Comment by tdolphin-org** [comment]
removed unnecessary prototype of main()

https://github.com/tdolphin-org/AmigaOS.MUI.cpp.wrapper/commit/510f4580842a0971b22ae70bb2ef5f7608bb0860
